### ISSUE TITLE
liquid: mismatch types in resources quota structs

### ISSUE THREAD

**Issue by jecluis** [sapcc/go-api-declarations#38]
While working on the `liquid-ceph` implementation, we have found a potentially problematic (albeit unlikely) issue with how quota values are defined.

See the specification for [`ResourceQuotaRequest`][_quota_request_url], where `Quota` is an unsigned 64-bit int.
Then, on [`ResourceUsageReport`][_usage_report_url], the value for `Quota` becomes a signed 64-bit int.

(This is also applicable to per-Availability Zone quota)

As one might see, this loss of precision may lead to an integer overflow when reporting quota on usage request.

Again, albeit this is unlikely due to storage capacity in real-life scenarios, it still feels odd that we are subject to this mismatch, loss of precision, and opening ourselves to unforeseen issues, now or in the future.

[_quota_request_url]: https://pkg.go.dev/github.com/sapcc/go-api-declarations/liquid#ResourceQuotaRequest
[_usage_report_url]: https://pkg.go.dev/github.com/sapcc/go-api-declarations/liquid#ResourceUsageReport

**Comment by majewsky** [comment]
Works as intended. OpenStack will report "no quota" as -1, so we have to use negative values for backend quotas, while Limes uses unsigned values for frontend quotas.
